### ISSUE TITLE
Something is wrong with the Q value prediction. 

### ISSUE THREAD

**Issue by shamanez** [manantomar/DSR#1]
In this [line](https://github.com/manantomar/DSR/blob/master/agent_dsr_ae_small.py#L215), you predict Q values by adding a fully connected layer. But it is wrong. Actually, you should multiply the SR representations with the weight vector to calculate the Q values.

**Comment by jisoolee0123** [comment]
I think there's nothing wrong..
mu_list[i] is the SR representation of the given state and i-th action.
Applying a fully connected layer to mu_list[i] without bias is the same as the multiplication of the mu_list[i] and 'reused' weight vector.

**Comment by shamanez** [comment]
but that the fully connected layers should be the same for each of your targets.

**Comment by manantomar** [comment]
That is why `reuse=True` for that operation

**Comment by shamanez** [comment]
Oh yes. Sorry I didn't notice that. :) well-done mate!
